###Login
POST  http://127.0.0.1:8000/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "juan@mail.com",
    "password": "12345"
}

###Profile
GET   http://127.0.0.1:8000/api/v1/auth/profile
Accept: application/json
Authorization: Bearer 4|Nd5WUZAJrGLzrL2ElO17JMHiDNa5I4Fosd1B63ZY9632bc6f


###Salir
GET   http://127.0.0.1:8000/api/v1/auth/logout
Accept: application/json
Authorization: Bearer 4|Nd5WUZAJrGLzrL2ElO17JMHiDNa5I4Fosd1B63ZY9632bc6f
